import { RotateCw } from "lucide-react";
import { WorkspaceDef } from "../types";

export const rotateWorkspace: WorkspaceDef = {
  id: "rotate",
  label: "Rotate · Scale",
  shortcut: "Alt+2",
  icon: RotateCw,
  previewDefault: true,
  sequence: "whenVideo",
  defaultLayout: {
    layout: "split",
    panes: ["Overlay before", "Overlay after"],
  },
  groups: [
    {
      title: "Source",
      params: [
        {
          key: "source",
          label: "Source",
          type: "choice",
          display: "segmented",
          options: [
            { value: "pair", label: "Pair" },
            { value: "video", label: "Video" },
            { value: "synthetic", label: "Generate" },
          ],
          default: "pair",
        },
        {
          key: "aId",
          label: "A",
          type: "media",
          accept: "image",
          when: (p) => p.source === "pair",
        },
        {
          key: "bId",
          label: "B",
          type: "media",
          accept: "image",
          when: (p) => p.source === "pair",
        },
        {
          key: "maxSide",
          label: "Working Size",
          type: "number",
          min: 320,
          max: 1280,
          step: 32,
          default: 704,
          unit: "px",
          when: (p) => p.source === "pair",
        },
        {
          key: "mediaId",
          label: "Video",
          type: "media",
          accept: "video",
          when: (p) => p.source === "video",
        },
        {
          key: "baseId",
          label: "Base",
          type: "media",
          accept: "image",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "angle",
          label: "Rotation",
          type: "number",
          min: -180,
          max: 180,
          step: 1,
          default: 20.0,
          unit: "°",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "scale",
          label: "Scale",
          type: "number",
          min: 0.7,
          max: 2.0,
          step: 0.01,
          default: 1.2,
          unit: "×",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "dy",
          label: "Δy",
          type: "number",
          min: -30,
          max: 30,
          step: 1,
          default: 9.0,
          unit: "px",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "dx",
          label: "Δx",
          type: "number",
          min: -30,
          max: 30,
          step: 1,
          default: -14.0,
          unit: "px",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "noise",
          label: "Noise σ",
          type: "number",
          min: 0,
          max: 0.2,
          step: 0.01,
          default: 0.0,
          when: (p) => p.source === "synthetic",
        },
      ],
    },
    {
      title: "Method",
      params: [
        {
          key: "robust",
          label: "Robust",
          type: "toggle",
          default: true,
        },
        {
          key: "nTheta",
          label: "θ Bins",
          type: "choice",
          options: [
            { value: "180", label: "180" },
            { value: "360", label: "360" },
            { value: "720", label: "720" },
            { value: "1080", label: "1080" },
          ],
          default: "720",
        },
        {
          key: "nRho",
          label: "ρ Bins",
          type: "choice",
          options: [
            { value: "128", label: "128" },
            { value: "256", label: "256" },
            { value: "512", label: "512" },
            { value: "768", label: "768" },
          ],
          default: "512",
        },
      ],
    },
    {
      title: "Display",
      params: [
        {
          key: "overlay",
          label: "Overlay",
          type: "registry",
          registry: "overlay",
          default: "anaglyph",
        },
      ],
    },
  ],
  toRequest: (p) => ({
    source: p.source,
    aId: p.aId || undefined,
    bId: p.bId || undefined,
    mediaId: p.mediaId || undefined,
    aIndex: p.aIndex ?? 0,
    bIndex: p.bIndex ?? 1,
    maxSide: p.maxSide,
    baseId: p.baseId || undefined,
    angle: p.angle,
    scale: p.scale,
    dy: p.dy,
    dx: p.dx,
    noise: p.noise,
    robust: p.robust,
    nTheta: parseInt(String(p.nTheta), 10) || 720,
    nRho: parseInt(String(p.nRho), 10) || 512,
    overlay: p.overlay,
  }),
};
