import { Highlighter } from "lucide-react";
import { WorkspaceDef } from "../types";

export const highlightWorkspace: WorkspaceDef = {
  id: "highlight",
  label: "Highlight",
  shortcut: "Alt+5",
  icon: Highlighter,
  previewDefault: false,
  sequence: "always",
  defaultLayout: {
    layout: "2up",
    panes: ["overlay", "Plate"],
  },
  frameLayer: "overlay",
  groups: [
    {
      title: "Source",
      params: [
        {
          key: "source",
          label: "Source",
          type: "choice",
          display: "segmented",
          options: [
            { value: "photos", label: "Photos" },
            { value: "video", label: "Video" },
            { value: "synthetic", label: "Generate" },
          ],
          default: "photos",
        },
        {
          key: "mediaIds",
          label: "Frames",
          type: "mediaMany",
          accept: "image",
          when: (p) => p.source === "photos",
        },
        {
          key: "maxSide",
          label: "Working Size",
          type: "number",
          min: 320,
          max: 1600,
          step: 32,
          default: 640,
          unit: "px",
          when: (p) => p.source === "photos",
        },
        {
          key: "colour",
          label: "Colour",
          type: "toggle",
          default: true,
          when: (p) => p.source === "photos",
        },
        {
          key: "mode",
          label: "Alignment",
          type: "choice",
          options: [
            { value: "translation", label: "Translation" },
            { value: "auto", label: "Auto" },
            { value: "similarity", label: "Similarity" },
          ],
          default: "auto",
          when: (p) => p.source === "photos",
        },
        {
          key: "mediaId",
          label: "Video",
          type: "media",
          accept: "video",
          when: (p) => p.source === "video",
        },
        {
          key: "frames",
          label: "Read",
          type: "number",
          min: 4,
          max: 60,
          step: 1,
          default: 24,
          when: (p) => p.source === "video",
        },
        {
          key: "step",
          label: "Every Nth",
          type: "number",
          min: 1,
          max: 10,
          step: 1,
          default: 2,
          when: (p) => p.source === "video",
        },
        {
          key: "baseId",
          label: "Base",
          type: "media",
          accept: "image",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "n",
          label: "Count",
          type: "number",
          min: 4,
          max: 24,
          step: 1,
          default: 12,
          when: (p) => p.source === "synthetic",
        },
        {
          key: "radius",
          label: "Radius",
          type: "number",
          min: 6,
          max: 60,
          step: 2,
          default: 26,
          unit: "px",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "noise",
          label: "Noise σ",
          type: "number",
          min: 0,
          max: 0.2,
          step: 0.005,
          default: 0.01,
          when: (p) => p.source === "synthetic",
        },
      ],
    },
    {
      title: "Method",
      params: [
        {
          key: "reducer",
          label: "Reducer",
          type: "registry",
          registry: "reducer",
          default: "shorth",
        },
      ],
    },
    {
      title: "Detection",
      params: [
        {
          key: "detector",
          label: "Detector",
          type: "registry",
          registry: "detector",
          default: "bandpass",
        },
        {
          key: "low",
          label: "Band Low",
          type: "number",
          min: 0.005,
          max: 0.1,
          step: 0.005,
          default: 0.02,
          when: (p) => p.detector === "bandpass",
        },
        {
          key: "high",
          label: "Band High",
          type: "number",
          min: 0.05,
          max: 0.45,
          step: 0.01,
          default: 0.2,
          when: (p) => p.detector === "bandpass",
        },
        {
          key: "k",
          label: "Threshold k",
          type: "number",
          min: 0.5,
          max: 8.0,
          step: 0.1,
          default: 3.0,
        },
        {
          key: "smooth",
          label: "Smooth",
          type: "number",
          min: 0.0,
          max: 5.0,
          step: 0.1,
          default: 1.5,
        },
        {
          key: "minArea",
          label: "Min Area",
          type: "number",
          min: 5,
          max: 500,
          step: 5,
          default: 40,
          unit: "px",
        },
      ],
    },
  ],
  toRequest: (p) => ({
    source: p.source,
    mediaIds: p.mediaIds || [],
    maxSide: p.maxSide,
    colour: p.colour,
    mode: p.mode,
    reducer: p.reducer,
    baseId: p.baseId || undefined,
    n: p.n,
    radius: p.radius,
    noise: p.noise,
    mediaId: p.mediaId || undefined,
    frames: p.frames,
    step: p.step,
    detector: p.detector,
    low: p.low,
    high: p.high,
    k: p.k,
    smooth: p.smooth,
    minArea: p.minArea,
  }),
};
