import { Move } from "lucide-react";
import { WorkspaceDef } from "../types";

export const alignWorkspace: WorkspaceDef = {
  id: "align",
  label: "Align",
  shortcut: "Alt+1",
  icon: Move,
  previewDefault: true,
  sequence: "whenVideo",
  defaultLayout: {
    layout: "2up",
    panes: ["A", "Overlay"],
  },
  groups: [
    {
      title: "Source",
      params: [
        {
          key: "source",
          label: "Source",
          type: "choice",
          display: "segmented",
          options: [
            { value: "pair", label: "Pair" },
            { value: "video", label: "Video" },
            { value: "synthetic", label: "Generate" },
          ],
          default: "synthetic",
        },
        {
          key: "aId",
          label: "A",
          type: "media",
          accept: "image",
          when: (p) => p.source === "pair",
        },
        {
          key: "bId",
          label: "B",
          type: "media",
          accept: "image",
          when: (p) => p.source === "pair",
        },
        {
          key: "mediaId",
          label: "Video",
          type: "media",
          accept: "video",
          when: (p) => p.source === "video",
        },
        {
          key: "baseId",
          label: "Base",
          type: "media",
          accept: "image",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "dy",
          label: "Δy",
          type: "number",
          min: -40,
          max: 40,
          step: 0.5,
          default: 12.5,
          unit: "px",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "dx",
          label: "Δx",
          type: "number",
          min: -40,
          max: 40,
          step: 0.5,
          default: -7.5,
          unit: "px",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "noise",
          label: "Noise σ",
          type: "number",
          min: 0,
          max: 0.4,
          step: 0.01,
          default: 0.0,
          when: (p) => p.source === "synthetic",
        },
      ],
    },
    {
      title: "Method",
      params: [
        {
          key: "window",
          label: "Window",
          type: "registry",
          registry: "window",
          default: "hann",
        },
        {
          key: "subpixel",
          label: "Sub-pixel",
          type: "registry",
          registry: "subpixel",
          default: "parabolic",
        },
        {
          key: "beta",
          label: "Magnitude β",
          type: "number",
          min: 0,
          max: 1,
          step: 0.05,
          default: 1.0,
        },
        {
          key: "lowpass",
          label: "Low-pass",
          type: "number",
          min: 0,
          max: 0.5,
          step: 0.01,
          default: 0.0,
        },
      ],
    },
    {
      title: "Display",
      params: [
        {
          key: "overlay",
          label: "Overlay",
          type: "registry",
          registry: "overlay",
          default: "anaglyph",
        },
        {
          key: "tile",
          label: "Tile",
          type: "number",
          min: 8,
          max: 128,
          step: 1,
          default: 32,
          when: (p) => p.overlay === "checkerboard",
        },
        {
          key: "alpha",
          label: "Opacity",
          type: "number",
          min: 0,
          max: 1,
          step: 0.05,
          default: 0.5,
          when: (p) => p.overlay === "blend",
        },
      ],
    },
  ],
  toRequest: (p) => ({
    source: p.source,
    aId: p.aId || undefined,
    bId: p.bId || undefined,
    mediaId: p.mediaId || undefined,
    aIndex: p.aIndex ?? 0,
    bIndex: p.bIndex ?? 1,
    baseId: p.baseId || undefined,
    dy: p.dy,
    dx: p.dx,
    noise: p.noise,
    window: p.window,
    subpixel: p.subpixel,
    beta: p.beta,
    lowpass: p.lowpass,
    overlay: p.overlay,
    tile: p.tile,
    alpha: p.alpha,
  }),
};
