import { Layers } from "lucide-react";
import { WorkspaceDef } from "../types";

export const stackWorkspace: WorkspaceDef = {
  id: "stack",
  label: "Stack",
  shortcut: "Alt+3",
  icon: Layers,
  previewDefault: false,
  sequence: "always",
  defaultLayout: {
    layout: "2up",
    panes: ["Raw", "Stacked"],
  },
  frameLayer: "frame",
  groups: [
    {
      title: "Source",
      params: [
        {
          key: "source",
          label: "Source",
          type: "choice",
          display: "segmented",
          options: [
            { value: "photos", label: "Photos" },
            { value: "video", label: "Video" },
            { value: "synthetic", label: "Generate" },
          ],
          default: "photos",
        },
        {
          key: "mediaIds",
          label: "Frames",
          type: "mediaMany",
          accept: "image",
          when: (p) => p.source === "photos",
        },
        {
          key: "cleanId",
          label: "Clean Ref",
          type: "media",
          accept: "image",
          when: (p) => p.source === "photos",
        },
        {
          key: "maxSide",
          label: "Working Size",
          type: "number",
          min: 320,
          max: 1600,
          step: 32,
          default: 800,
          unit: "px",
          when: (p) => p.source === "photos",
        },
        {
          key: "colour",
          label: "Colour",
          type: "toggle",
          default: true,
          when: (p) => p.source === "photos",
        },
        {
          key: "mediaId",
          label: "Video",
          type: "media",
          accept: "video",
          when: (p) => p.source === "video",
        },
        {
          key: "baseId",
          label: "Base",
          type: "media",
          accept: "image",
          when: (p) => p.source === "synthetic",
        },
        {
          key: "n",
          label: "Count",
          type: "number",
          min: 2,
          max: 32,
          step: 1,
          default: 16,
          when: (p) => p.source === "synthetic",
        },
        {
          key: "noise",
          label: "Noise σ",
          type: "number",
          min: 0,
          max: 0.4,
          step: 0.01,
          default: 0.12,
          when: (p) => p.source === "synthetic",
        },
        {
          key: "shift",
          label: "Max Shift",
          type: "number",
          min: 0,
          max: 15,
          step: 0.5,
          default: 5.0,
          unit: "px",
          when: (p) => p.source === "synthetic",
        },
      ],
    },
    {
      title: "Method",
      params: [
        {
          key: "reducer",
          label: "Reducer",
          type: "registry",
          registry: "reducer",
          default: "mean",
        },
        {
          key: "align",
          label: "Align",
          type: "toggle",
          default: true,
        },
        {
          key: "compare",
          label: "Compare",
          type: "toggle",
          default: true,
        },
      ],
    },
  ],
  toRequest: (p) => ({
    source: p.source,
    mediaIds: p.mediaIds || [],
    maxSide: p.maxSide,
    colour: p.colour,
    cleanId: p.cleanId || undefined,
    mediaId: p.mediaId || undefined,
    frames: p.frames,
    step: p.step,
    baseId: p.baseId || undefined,
    n: p.n,
    noise: p.noise,
    shift: p.shift,
    reducer: p.reducer,
    align: p.align,
    compare: p.compare,
  }),
};
